package org.itri.view.humanhealth.hibernate;
// Generated 2020/4/24 �U�� 08:59:27 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditTrail generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "audit_trail")
public class AuditTrail implements java.io.Serializable {

	private long auditTrailId;
	private String executeUser;
	private String executeUserRole;
	private Date executeTimestamp;
	private String executeMethod;
	private String executeAction;
	private String executeParameter;
	private String executeResult;

	public AuditTrail() {
	}

	public AuditTrail(long auditTrailId, String executeUser, String executeUserRole, Date executeTimestamp,
			String executeMethod, String executeAction, String executeParameter, String executeResult) {
		this.auditTrailId = auditTrailId;
		this.executeUser = executeUser;
		this.executeUserRole = executeUserRole;
		this.executeTimestamp = executeTimestamp;
		this.executeMethod = executeMethod;
		this.executeAction = executeAction;
		this.executeParameter = executeParameter;
		this.executeResult = executeResult;
	}

	@SequenceGenerator(name="audit_trail_seq", sequenceName="audit_trail_audit_trail_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="audit_trail_seq")	@Id

	@Column(name = "audit_trail_id", unique = true, nullable = false)
	public long getAuditTrailId() {
		return this.auditTrailId;
	}

	public void setAuditTrailId(long auditTrailId) {
		this.auditTrailId = auditTrailId;
	}

	@Column(name = "execute_user", nullable = false, length = 128)
	public String getExecuteUser() {
		return this.executeUser;
	}

	public void setExecuteUser(String executeUser) {
		this.executeUser = executeUser;
	}

	@Column(name = "execute_user_role", nullable = false, length = 128)
	public String getExecuteUserRole() {
		return this.executeUserRole;
	}

	public void setExecuteUserRole(String executeUserRole) {
		this.executeUserRole = executeUserRole;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "execute_timestamp", nullable = false, length = 29)
	public Date getExecuteTimestamp() {
		return this.executeTimestamp;
	}

	public void setExecuteTimestamp(Date executeTimestamp) {
		this.executeTimestamp = executeTimestamp;
	}

	@Column(name = "execute_method", nullable = false, length = 128)
	public String getExecuteMethod() {
		return this.executeMethod;
	}

	public void setExecuteMethod(String executeMethod) {
		this.executeMethod = executeMethod;
	}

	@Column(name = "execute_action", nullable = false, length = 64)
	public String getExecuteAction() {
		return this.executeAction;
	}

	public void setExecuteAction(String executeAction) {
		this.executeAction = executeAction;
	}

	@Column(name = "execute_parameter", nullable = false, length = 1024)
	public String getExecuteParameter() {
		return this.executeParameter;
	}

	public void setExecuteParameter(String executeParameter) {
		this.executeParameter = executeParameter;
	}

	@Column(name = "execute_result", nullable = false, length = 64)
	public String getExecuteResult() {
		return this.executeResult;
	}

	public void setExecuteResult(String executeResult) {
		this.executeResult = executeResult;
	}

}
