package org.itri.view.humanhealth.hibernate;
// Generated 2020/7/27 �U�� 04:58:44 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DeviceStatus generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "device_status")
public class DeviceStatus implements java.io.Serializable {

	private long deviceStatusId;
	private String statusName;
	private boolean isDeleted;

	public DeviceStatus() {
	}

	public DeviceStatus(long deviceStatusId, String statusName, boolean isDeleted) {
		this.deviceStatusId = deviceStatusId;
		this.statusName = statusName;
		this.isDeleted = isDeleted;
	}

	@SequenceGenerator(name="device_status_seq", sequenceName="device_status_device_status_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="device_status_seq")	@Id

	@Column(name = "device_status_id", unique = true, nullable = false)
	public long getDeviceStatusId() {
		return this.deviceStatusId;
	}

	public void setDeviceStatusId(long deviceStatusId) {
		this.deviceStatusId = deviceStatusId;
	}

	@Column(name = "status_name", nullable = false, length = 64)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
