package org.itri.view.humanhealth.hibernate;
// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HealthStatus generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "health_status")
public class HealthStatus implements java.io.Serializable {

	private long healthStatusId;
	private String statusCode;
	private String status;
	private boolean isDeleted;

	public HealthStatus() {
	}

	public HealthStatus(long healthStatusId, String statusCode, String status, boolean isDeleted) {
		this.healthStatusId = healthStatusId;
		this.statusCode = statusCode;
		this.status = status;
		this.isDeleted = isDeleted;
	}

	@SequenceGenerator(name="health_status_seq", sequenceName="health_status_health_status_id_seq")	@GeneratedValue(generator="health_status_seq")	@Id

	@Column(name = "health_status_id", unique = true, nullable = false)
	public long getHealthStatusId() {
		return this.healthStatusId;
	}

	public void setHealthStatusId(long healthStatusId) {
		this.healthStatusId = healthStatusId;
	}

	@Column(name = "status_code", nullable = false, length = 10)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "status", nullable = false, length = 64)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
