package org.itri.view.humanhealth.hibernate;
// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NewsMathOperator generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "news_math_operator")
public class NewsMathOperator implements java.io.Serializable {

	private long newsMathOperatorId;
	private String operator;
	private Set<NewsWarningCondition> newsWarningConditions = new HashSet<NewsWarningCondition>(0);

	public NewsMathOperator() {
	}

	public NewsMathOperator(long newsMathOperatorId, String operator) {
		this.newsMathOperatorId = newsMathOperatorId;
		this.operator = operator;
	}

	public NewsMathOperator(long newsMathOperatorId, String operator, Set<NewsWarningCondition> newsWarningConditions) {
		this.newsMathOperatorId = newsMathOperatorId;
		this.operator = operator;
		this.newsWarningConditions = newsWarningConditions;
	}

	@SequenceGenerator(name="news_math_operator_seq", sequenceName="news_math_operator_news_math_operator_id_seq")	@GeneratedValue(generator="news_math_operator_seq")	@Id

	@Column(name = "news_math_operator_id", unique = true, nullable = false)
	public long getNewsMathOperatorId() {
		return this.newsMathOperatorId;
	}

	public void setNewsMathOperatorId(long newsMathOperatorId) {
		this.newsMathOperatorId = newsMathOperatorId;
	}

	@Column(name = "operator", nullable = false, length = 128)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "newsMathOperator")
	public Set<NewsWarningCondition> getNewsWarningConditions() {
		return this.newsWarningConditions;
	}

	public void setNewsWarningConditions(Set<NewsWarningCondition> newsWarningConditions) {
		this.newsWarningConditions = newsWarningConditions;
	}

}
