package org.itri.view.humanhealth.hibernate;
// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NewsScoreThreshold generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "news_score_threshold")
public class NewsScoreThreshold implements java.io.Serializable {

	private long newsScoreThresholdId;
	private String lowBound;
	private String highBound;
	private String score;
	private boolean isDeleted;
	private String healthTypeId;

	public NewsScoreThreshold() {
	}

	public NewsScoreThreshold(long newsScoreThresholdId, String score, boolean isDeleted, String healthTypeId) {
		this.newsScoreThresholdId = newsScoreThresholdId;
		this.score = score;
		this.isDeleted = isDeleted;
		this.healthTypeId = healthTypeId;
	}

	public NewsScoreThreshold(long newsScoreThresholdId, String lowBound, String highBound, String score,
			boolean isDeleted, String healthTypeId) {
		this.newsScoreThresholdId = newsScoreThresholdId;
		this.lowBound = lowBound;
		this.highBound = highBound;
		this.score = score;
		this.isDeleted = isDeleted;
		this.healthTypeId = healthTypeId;
	}

	@SequenceGenerator(name="news_score_threshold_seq", sequenceName="news_score_threshold_news_score_threshold_id_seq")	@GeneratedValue(generator="news_score_threshold_seq")	@Id

	@Column(name = "news_score_threshold_id", unique = true, nullable = false)
	public long getNewsScoreThresholdId() {
		return this.newsScoreThresholdId;
	}

	public void setNewsScoreThresholdId(long newsScoreThresholdId) {
		this.newsScoreThresholdId = newsScoreThresholdId;
	}

	@Column(name = "low_bound", length = 32)
	public String getLowBound() {
		return this.lowBound;
	}

	public void setLowBound(String lowBound) {
		this.lowBound = lowBound;
	}

	@Column(name = "high_bound", length = 32)
	public String getHighBound() {
		return this.highBound;
	}

	public void setHighBound(String highBound) {
		this.highBound = highBound;
	}

	@Column(name = "score", nullable = false, length = 32)
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "health_type_id", nullable = false, length = 10)
	public String getHealthTypeId() {
		return this.healthTypeId;
	}

	public void setHealthTypeId(String healthTypeId) {
		this.healthTypeId = healthTypeId;
	}

}
