package org.itri.view.humanhealth.hibernate;

import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NewsRecord generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "news_record")
public class NewsRecord implements java.io.Serializable {

	private long newsRecordId;
	private Patient patient;
	private Integer newsScore;
	private Date timeCreated;

	public NewsRecord() {
	}
	
	public NewsRecord(Patient patient, Integer newsScore, Date timeCreated) {
		this.patient = patient;
		this.newsScore = newsScore;
		this.timeCreated = timeCreated;
	}

	public NewsRecord(long newsRecordId, Patient patient, Integer newsScore) {
		this.newsRecordId = newsRecordId;
		this.patient = patient;
		this.newsScore = newsScore;
	}

	public NewsRecord(long newsRecordId, Patient patient, Integer newsScore, Date timeCreated) {
		this.newsRecordId = newsRecordId;
		this.patient = patient;
		this.newsScore = newsScore;
		this.timeCreated = timeCreated;
	}

	@SequenceGenerator(name="news_record_seq", sequenceName="news_record_news_record_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="news_record_seq")	@Id

	@Column(name = "news_record_id", unique = true, nullable = false)
	public long getNewsRecordId() {
		return this.newsRecordId;
	}

	public void setNewsRecordId(long newsRecordId) {
		this.newsRecordId = newsRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "news_score")
	public Integer getNewsScore() {
		return this.newsScore;
	}

	public void setNewsScore(Integer newsScore) {
		this.newsScore = newsScore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", length = 29)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

}
