package org.itri.view.humanhealth.hibernate;
// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OximeterRecord generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "oximeter_record")
public class OximeterRecord implements java.io.Serializable {

	private long oximeterRecordId;
	private Sensor sensor;
	private String oximeterData;
	private String heartRateData;
	private String breathData;
	private String batteryLevel;
	private String oximeterStatus;
	private String heartRateStatus;
	private String breathStatus;
	private Date timeCreated;

	public OximeterRecord() {
	}

	public OximeterRecord(long oximeterRecordId, Sensor sensor, String oximeterData, String heartRateData,
			String breathData, String batteryLevel, String oximeterStatus, String heartRateStatus, String breathStatus,
			Date timeCreated) {
		this.oximeterRecordId = oximeterRecordId;
		this.sensor = sensor;
		this.oximeterData = oximeterData;
		this.heartRateData = heartRateData;
		this.breathData = breathData;
		this.batteryLevel = batteryLevel;
		this.oximeterStatus = oximeterStatus;
		this.heartRateStatus = heartRateStatus;
		this.breathStatus = breathStatus;
		this.timeCreated = timeCreated;
	}

	@SequenceGenerator(name="oximeter_record_seq", sequenceName="oximeter_record_oximeter_record_id_seq")	@GeneratedValue(generator="oximeter_record_seq")	@Id

	@Column(name = "oximeter_record_id", unique = true, nullable = false)
	public long getOximeterRecordId() {
		return this.oximeterRecordId;
	}

	public void setOximeterRecordId(long oximeterRecordId) {
		this.oximeterRecordId = oximeterRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sensor_id", nullable = false)
	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	@Column(name = "oximeter_data", nullable = false, length = 64)
	public String getOximeterData() {
		return this.oximeterData;
	}

	public void setOximeterData(String oximeterData) {
		this.oximeterData = oximeterData;
	}

	@Column(name = "heart_rate_data", nullable = false, length = 64)
	public String getHeartRateData() {
		return this.heartRateData;
	}

	public void setHeartRateData(String heartRateData) {
		this.heartRateData = heartRateData;
	}

	@Column(name = "breath_data", nullable = false, length = 64)
	public String getBreathData() {
		return this.breathData;
	}

	public void setBreathData(String breathData) {
		this.breathData = breathData;
	}

	@Column(name = "battery_level", nullable = false, length = 64)
	public String getBatteryLevel() {
		return this.batteryLevel;
	}

	public void setBatteryLevel(String batteryLevel) {
		this.batteryLevel = batteryLevel;
	}

	@Column(name = "oximeter_status", nullable = false, length = 32)
	public String getOximeterStatus() {
		return this.oximeterStatus;
	}

	public void setOximeterStatus(String oximeterStatus) {
		this.oximeterStatus = oximeterStatus;
	}

	@Column(name = "heart_rate_status", nullable = false, length = 32)
	public String getHeartRateStatus() {
		return this.heartRateStatus;
	}

	public void setHeartRateStatus(String heartRateStatus) {
		this.heartRateStatus = heartRateStatus;
	}

	@Column(name = "breath_status", nullable = false, length = 32)
	public String getBreathStatus() {
		return this.breathStatus;
	}

	public void setBreathStatus(String breathStatus) {
		this.breathStatus = breathStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", nullable = false, length = 29)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

}
