package org.itri.view.humanhealth.hibernate;
// Generated 2020/4/24 �U�� 08:59:27 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Patient2sensor generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "patient2sensor")
public class Patient2sensor implements java.io.Serializable {

	private long patient2sensorId;
	private Patient patient;
	private Sensor sensor;

	public Patient2sensor() {
	}

	public Patient2sensor(long patient2sensorId, Patient patient, Sensor sensor) {
		this.patient2sensorId = patient2sensorId;
		this.patient = patient;
		this.sensor = sensor;
	}

	@SequenceGenerator(name="patient2sensor_seq", sequenceName="patient2sensor_patient2sensor_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="patient2sensor_seq")	@Id

	@Column(name = "patient2sensor_id", unique = true, nullable = false)
	public long getPatient2sensorId() {
		return this.patient2sensorId;
	}

	public void setPatient2sensorId(long patient2sensorId) {
		this.patient2sensorId = patient2sensorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sensor_id", nullable = false)
	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

}
