package org.itri.view.humanhealth.hibernate;
// Generated 2020/4/24 �U�� 08:08:16 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * Patient generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "patient")
public class Patient implements java.io.Serializable {

	private long patientId;
	private Room room;
	private Gateway gateway;
	private String heartRateStatus;
	private Integer heartRateNewsScore;
	private String oximeterStatus;
	private Integer oximeterNewsScore;
	private String bodyTempStatus;
	private Integer bodyTempNewsScore;
	private String breathStatus;
	private Integer breathNewsScore;
	private String pmFiveStatus;
	private String mattressStatus;
	private Integer totalNewsScore;
	private Date lastUpdated;
	private Date timeCreated;
	private boolean isDeleted;
	private Set<PatientInfo> patientInfos = new HashSet<PatientInfo>(0);
	private Set<RtTempPadRecord> rtTempPadRecords = new HashSet<RtTempPadRecord>(0);
	private Set<RtHeartRhythmRecord> rtHeartRhythmRecords = new HashSet<RtHeartRhythmRecord>(0);
	private Set<MattressRecord> mattressRecords = new HashSet<MattressRecord>(0);
	private Set<RtMattressRecord> rtMattressRecords = new HashSet<RtMattressRecord>(0);
	private Set<OximeterRecord> oximeterRecords = new HashSet<OximeterRecord>(0);
	private Set<NewsRecord> newsRecords = new HashSet<NewsRecord>(0);
	private Set<Patient2sensor> patient2sensors = new HashSet<Patient2sensor>(0);
	private Set<PmFiveRecord> pmFiveRecords = new HashSet<PmFiveRecord>(0);
	private Set<RtPmFiveRecord> rtPmFiveRecords = new HashSet<RtPmFiveRecord>(0);
	private Set<PatientThreshold> patientThresholds = new HashSet<PatientThreshold>(0);
	private Set<RtRespirationCoughRecord> rtRespirationCoughRecords = new HashSet<RtRespirationCoughRecord>(0);
	private Set<TempPadRecord> tempPadRecords = new HashSet<TempPadRecord>(0);
	private Set<HeartRhythmRecord> heartRhythmRecords = new HashSet<HeartRhythmRecord>(0);
	private Set<RespirationCoughRecord> respirationCoughRecords = new HashSet<RespirationCoughRecord>(0);
	private Set<RtOximeterRecord> rtOximeterRecords = new HashSet<RtOximeterRecord>(0);
	private Set<SurveyResult> surveyResults = new HashSet<SurveyResult>(0);

	public Patient() {
	}

	public Patient(Room room, String heartRateStatus, Integer heartRateNewsScore, String oximeterStatus, 
			Integer oximeterNewsScore, String bodyTempStatus, Integer bodyTempNewsScore, 
			String breathStatus, Integer breathNewsScore, String pmFiveStatus, String mattressStatus, 
			Integer totalNewsScore, Date lastUpdated, Date timeCreated, boolean isDeleted) {
		this.room = room;
		this.heartRateStatus = heartRateStatus;
		this.heartRateNewsScore = heartRateNewsScore;
		this.oximeterStatus = oximeterStatus;
		this.oximeterNewsScore = oximeterNewsScore;
		this.bodyTempStatus = bodyTempStatus;
		this.bodyTempNewsScore = bodyTempNewsScore;
		this.breathStatus = breathStatus;
		this.breathNewsScore = breathNewsScore;
		this.pmFiveStatus = pmFiveStatus;
		this.mattressStatus = mattressStatus;
		this.totalNewsScore = totalNewsScore;
		this.lastUpdated = lastUpdated;
		this.timeCreated = timeCreated;
		this.isDeleted = isDeleted;
	}
	
	public Patient(long patientId, Room room, Gateway gateway, String heartRateStatus, String oximeterStatus, String bodyTempStatus,
			String breathStatus, String pmFiveStatus, String mattressStatus, Integer totalNewsScore, 
			Date timeCreated, boolean isDeleted) {
		this.patientId = patientId;
		this.room = room;
		this.gateway = gateway;
		this.heartRateStatus = heartRateStatus;
		this.oximeterStatus = oximeterStatus;
		this.bodyTempStatus = bodyTempStatus;
		this.breathStatus = breathStatus;
		this.pmFiveStatus = pmFiveStatus;
		this.mattressStatus = mattressStatus;
		this.totalNewsScore = totalNewsScore;
		this.timeCreated = timeCreated;
		this.isDeleted = isDeleted;
	}

	public Patient(long patientId, Room room, String heartRateStatus, String oximeterStatus, String bodyTempStatus,
			String breathStatus, String pmFiveStatus, String mattressStatus, Integer totalNewsScore, 
			Date timeCreated, boolean isDeleted,
			Set<PatientInfo> patientInfos, Set<RtTempPadRecord> rtTempPadRecords,
			Set<RtHeartRhythmRecord> rtHeartRhythmRecords, Set<MattressRecord> mattressRecords,
			Set<RtMattressRecord> rtMattressRecords, Set<OximeterRecord> oximeterRecords,
			Set<Patient2sensor> patient2sensors, Set<PmFiveRecord> pmFiveRecords, Set<RtPmFiveRecord> rtPmFiveRecords,
			Set<PatientThreshold> patientThresholds, Set<RtRespirationCoughRecord> rtRespirationCoughRecords,
			Set<TempPadRecord> tempPadRecords, Set<HeartRhythmRecord> heartRhythmRecords,
			Set<RespirationCoughRecord> respirationCoughRecords, Set<RtOximeterRecord> rtOximeterRecords) {
		this.patientId = patientId;
		this.room = room;
		this.heartRateStatus = heartRateStatus;
		this.oximeterStatus = oximeterStatus;
		this.bodyTempStatus = bodyTempStatus;
		this.breathStatus = breathStatus;
		this.pmFiveStatus = pmFiveStatus;
		this.mattressStatus = mattressStatus;
		this.totalNewsScore = totalNewsScore;
		this.timeCreated = timeCreated;
		this.isDeleted = isDeleted;
		this.patientInfos = patientInfos;
		this.rtTempPadRecords = rtTempPadRecords;
		this.rtHeartRhythmRecords = rtHeartRhythmRecords;
		this.mattressRecords = mattressRecords;
		this.rtMattressRecords = rtMattressRecords;
		this.oximeterRecords = oximeterRecords;
		this.patient2sensors = patient2sensors;
		this.pmFiveRecords = pmFiveRecords;
		this.rtPmFiveRecords = rtPmFiveRecords;
		this.patientThresholds = patientThresholds;
		this.rtRespirationCoughRecords = rtRespirationCoughRecords;
		this.tempPadRecords = tempPadRecords;
		this.heartRhythmRecords = heartRhythmRecords;
		this.respirationCoughRecords = respirationCoughRecords;
		this.rtOximeterRecords = rtOximeterRecords;
	}

	@SequenceGenerator(name="patient_seq", sequenceName="patient_patient_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="patient_seq")	@Id

	@Column(name = "patient_id", unique = true, nullable = false)
	public long getPatientId() {
		return this.patientId;
	}

	public void setPatientId(long patientId) {
		this.patientId = patientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gateway_id")
	public Gateway getGateway() {
		return this.gateway;
	}

	public void setGateway(Gateway gateway) {
		this.gateway = gateway;
	}

	@Column(name = "heart_rate_status", nullable = false, length = 32)
	public String getHeartRateStatus() {
		return this.heartRateStatus;
	}

	public void setHeartRateStatus(String heartRateStatus) {
		this.heartRateStatus = heartRateStatus;
	}
	
	@Column(name = "heart_rate_news_score")
	public Integer getHeartRateNewsScore() {
		return this.heartRateNewsScore;
	}

	public void setHeartRateNewsScore(Integer heartRateNewsScore) {
		this.heartRateNewsScore = heartRateNewsScore;
	}

	@Column(name = "oximeter_status", nullable = false, length = 32)
	public String getOximeterStatus() {
		return this.oximeterStatus;
	}

	public void setOximeterStatus(String oximeterStatus) {
		this.oximeterStatus = oximeterStatus;
	}
	
	@Column(name = "oximeter_news_score")
	public Integer getOximeterNewsScore() {
		return this.oximeterNewsScore;
	}

	public void setOximeterNewsScore(Integer oximeterNewsScore) {
		this.oximeterNewsScore = oximeterNewsScore;
	}

	@Column(name = "body_temp_status", nullable = false, length = 32)
	public String getBodyTempStatus() {
		return this.bodyTempStatus;
	}

	public void setBodyTempStatus(String bodyTempStatus) {
		this.bodyTempStatus = bodyTempStatus;
	}
	
	@Column(name = "body_temp_news_score")
	public Integer getBodyTempNewsScore() {
		return this.bodyTempNewsScore;
	}

	public void setBodyTempNewsScore(Integer bodyTempNewsScore) {
		this.bodyTempNewsScore = bodyTempNewsScore;
	}

	@Column(name = "breath_status", nullable = false, length = 32)
	public String getBreathStatus() {
		return this.breathStatus;
	}

	public void setBreathStatus(String breathStatus) {
		this.breathStatus = breathStatus;
	}
	
	@Column(name = "breath_news_score")
	public Integer getBreathNewsScore() {
		return this.breathNewsScore;
	}

	public void setBreathNewsScore(Integer breathNewsScore) {
		this.breathNewsScore = breathNewsScore;
	}

	@Column(name = "pm_five_status", nullable = false, length = 32)
	public String getPmFiveStatus() {
		return this.pmFiveStatus;
	}

	public void setPmFiveStatus(String pmFiveStatus) {
		this.pmFiveStatus = pmFiveStatus;
	}

	@Column(name = "mattress_status", nullable = false, length = 32)
	public String getMattressStatus() {
		return this.mattressStatus;
	}

	public void setMattressStatus(String mattressStatus) {
		this.mattressStatus = mattressStatus;
	}
	
	@Column(name = "total_news_score", nullable = false)
	public Integer getTotalNewsScore() {
		return this.totalNewsScore;
	}

	public void setTotalNewsScore(Integer totalNewsScore) {
		this.totalNewsScore = totalNewsScore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", nullable = false, length = 29)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<PatientInfo> getPatientInfos() {
		return this.patientInfos;
	}

	public void setPatientInfos(Set<PatientInfo> patientInfos) {
		this.patientInfos = patientInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<RtTempPadRecord> getRtTempPadRecords() {
		return this.rtTempPadRecords;
	}

	public void setRtTempPadRecords(Set<RtTempPadRecord> rtTempPadRecords) {
		this.rtTempPadRecords = rtTempPadRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<RtHeartRhythmRecord> getRtHeartRhythmRecords() {
		return this.rtHeartRhythmRecords;
	}

	public void setRtHeartRhythmRecords(Set<RtHeartRhythmRecord> rtHeartRhythmRecords) {
		this.rtHeartRhythmRecords = rtHeartRhythmRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<MattressRecord> getMattressRecords() {
		return this.mattressRecords;
	}

	public void setMattressRecords(Set<MattressRecord> mattressRecords) {
		this.mattressRecords = mattressRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<RtMattressRecord> getRtMattressRecords() {
		return this.rtMattressRecords;
	}

	public void setRtMattressRecords(Set<RtMattressRecord> rtMattressRecords) {
		this.rtMattressRecords = rtMattressRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<OximeterRecord> getOximeterRecords() {
		return this.oximeterRecords;
	}

	public void setOximeterRecords(Set<OximeterRecord> oximeterRecords) {
		this.oximeterRecords = oximeterRecords;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<NewsRecord> getNewsRecords() {
		return this.newsRecords;
	}

	public void setNewsRecords(Set<NewsRecord> newsRecords) {
		this.newsRecords = newsRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Patient2sensor> getPatient2sensors() {
		return this.patient2sensors;
	}

	public void setPatient2sensors(Set<Patient2sensor> patient2sensors) {
		this.patient2sensors = patient2sensors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<PmFiveRecord> getPmFiveRecords() {
		return this.pmFiveRecords;
	}

	public void setPmFiveRecords(Set<PmFiveRecord> pmFiveRecords) {
		this.pmFiveRecords = pmFiveRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<RtPmFiveRecord> getRtPmFiveRecords() {
		return this.rtPmFiveRecords;
	}

	public void setRtPmFiveRecords(Set<RtPmFiveRecord> rtPmFiveRecords) {
		this.rtPmFiveRecords = rtPmFiveRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<PatientThreshold> getPatientThresholds() {
		return this.patientThresholds;
	}

	public void setPatientThresholds(Set<PatientThreshold> patientThresholds) {
		this.patientThresholds = patientThresholds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<RtRespirationCoughRecord> getRtRespirationCoughRecords() {
		return this.rtRespirationCoughRecords;
	}

	public void setRtRespirationCoughRecords(Set<RtRespirationCoughRecord> rtRespirationCoughRecords) {
		this.rtRespirationCoughRecords = rtRespirationCoughRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<TempPadRecord> getTempPadRecords() {
		return this.tempPadRecords;
	}

	public void setTempPadRecords(Set<TempPadRecord> tempPadRecords) {
		this.tempPadRecords = tempPadRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<HeartRhythmRecord> getHeartRhythmRecords() {
		return this.heartRhythmRecords;
	}

	public void setHeartRhythmRecords(Set<HeartRhythmRecord> heartRhythmRecords) {
		this.heartRhythmRecords = heartRhythmRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<RespirationCoughRecord> getRespirationCoughRecords() {
		return this.respirationCoughRecords;
	}

	public void setRespirationCoughRecords(Set<RespirationCoughRecord> respirationCoughRecords) {
		this.respirationCoughRecords = respirationCoughRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<RtOximeterRecord> getRtOximeterRecords() {
		return this.rtOximeterRecords;
	}

	public void setRtOximeterRecords(Set<RtOximeterRecord> rtOximeterRecords) {
		this.rtOximeterRecords = rtOximeterRecords;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<SurveyResult> getSurveyResults() {
		return this.surveyResults;
	}

	public void setSurveyResults(Set<SurveyResult> surveyResults) {
		this.surveyResults = surveyResults;
	}

}
