package org.itri.view.humanhealth.hibernate;
// Generated 2020/4/24 �U�� 08:59:27 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientThreshold generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "patient_threshold")
public class PatientThreshold implements java.io.Serializable {

	private long patientThresholdId;
	private Users users;
	private HealthType healthType;
	private Patient patient;
	private Sensor sensor;
	private String warningLow;
	private String warningHigh;
	private String criticalLow;
	private String criticalHigh;
	private String durationTimes;
	private String dataName;
	private Date timeCreated;
	private Date lastUpdated;
	private boolean isDeleted;

	public PatientThreshold() {
	}

	public PatientThreshold(long patientThresholdId, Users users, HealthType healthType, Patient patient, Sensor sensor,
			String durationTimes, Date timeCreated, boolean isDeleted) {
		this.patientThresholdId = patientThresholdId;
		this.users = users;
		this.healthType = healthType;
		this.patient = patient;
		this.sensor = sensor;
		this.durationTimes = durationTimes;
		this.timeCreated = timeCreated;
		this.isDeleted = isDeleted;
	}

	public PatientThreshold(long patientThresholdId, Users users, HealthType healthType, Patient patient, Sensor sensor,
			String warningLow, String warningHigh, String criticalLow, String criticalHigh, String durationTimes,
			String dataName, Date timeCreated, Date lastUpdated, boolean isDeleted) {
		this.patientThresholdId = patientThresholdId;
		this.users = users;
		this.healthType = healthType;
		this.patient = patient;
		this.sensor = sensor;
		this.warningLow = warningLow;
		this.warningHigh = warningHigh;
		this.criticalLow = criticalLow;
		this.criticalHigh = criticalHigh;
		this.durationTimes = durationTimes;
		this.dataName = dataName;
		this.timeCreated = timeCreated;
		this.lastUpdated = lastUpdated;
		this.isDeleted = isDeleted;
	}

	@SequenceGenerator(name="patient_threshold_seq", sequenceName="patient_threshold_patient_threshold_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="patient_threshold_seq")	@Id

	@Column(name = "patient_threshold_id", unique = true, nullable = false)
	public long getPatientThresholdId() {
		return this.patientThresholdId;
	}

	public void setPatientThresholdId(long patientThresholdId) {
		this.patientThresholdId = patientThresholdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "health_type_id", nullable = false)
	public HealthType getHealthType() {
		return this.healthType;
	}

	public void setHealthType(HealthType healthType) {
		this.healthType = healthType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sensor_id", nullable = false)
	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	@Column(name = "warning_low", length = 256)
	public String getWarningLow() {
		return this.warningLow;
	}

	public void setWarningLow(String warningLow) {
		this.warningLow = warningLow;
	}

	@Column(name = "warning_high", length = 256)
	public String getWarningHigh() {
		return this.warningHigh;
	}

	public void setWarningHigh(String warningHigh) {
		this.warningHigh = warningHigh;
	}

	@Column(name = "critical_low", length = 256)
	public String getCriticalLow() {
		return this.criticalLow;
	}

	public void setCriticalLow(String criticalLow) {
		this.criticalLow = criticalLow;
	}

	@Column(name = "critical_high", length = 256)
	public String getCriticalHigh() {
		return this.criticalHigh;
	}

	public void setCriticalHigh(String criticalHigh) {
		this.criticalHigh = criticalHigh;
	}

	@Column(name = "duration_times", nullable = false, length = 10)
	public String getDurationTimes() {
		return this.durationTimes;
	}

	public void setDurationTimes(String durationTimes) {
		this.durationTimes = durationTimes;
	}

	@Column(name = "data_name", length = 256)
	public String getDataName() {
		return this.dataName;
	}

	public void setDataName(String dataName) {
		this.dataName = dataName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", nullable = false, length = 29)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
