package org.itri.view.humanhealth.hibernate;

// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;
import javax.persistence.SequenceGenerator;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Room generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "room")
public class Room implements java.io.Serializable {

	private long roomId;
	private String roomNum;
	private boolean isFull;
	private Date lastUpdated;
	private Set<RoomGroup> roomGroups = new HashSet<RoomGroup>(0);
	private Set<Combination> combinations = new HashSet<Combination>(0);

	public Room() {
	}

	public Room(String roomNum, boolean isFull) {
		this.roomNum = roomNum;
		this.isFull = isFull;
	}

	public Room(long roomId, Users users, String roomNum, boolean isFull) {
		this.roomId = roomId;
		this.roomNum = roomNum;
		this.isFull = isFull;
	}

	public Room(long roomId, String roomNum, boolean isFull, Date lastUpdated, Set<Combination> combinations) {
		this.roomId = roomId;
		this.roomNum = roomNum;
		this.isFull = isFull;
		this.lastUpdated = lastUpdated;
		this.combinations = combinations;
	}

	@SequenceGenerator(name = "room_seq", sequenceName = "room_room_id_seq")
	@GeneratedValue(generator = "room_seq")
	@Id

	@Column(name = "room_id", unique = true, nullable = false)
	public long getRoomId() {
		return this.roomId;
	}

	public void setRoomId(long roomId) {
		this.roomId = roomId;
	}

	@Column(name = "room_num", nullable = false, length = 128)
	public String getRoomNum() {
		return this.roomNum;
	}

	public void setRoomNum(String roomNum) {
		this.roomNum = roomNum;
	}

	@Column(name = "is_full", nullable = false)
	public boolean isIsFull() {
		return this.isFull;
	}

	public void setIsFull(boolean isFull) {
		this.isFull = isFull;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<RoomGroup> getRoomGroups() {
		return this.roomGroups;
	}

	public void setRoomGroups(Set<RoomGroup> roomGroups) {
		this.roomGroups = roomGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Combination> getCombinations() {
		return this.combinations;
	}

	public void setCombinations(Set<Combination> combinations) {
		this.combinations = combinations;
	}

}
