package org.itri.view.humanhealth.hibernate;
// Generated 2020/12/1 �U�� 01:43:50 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoomGroup generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "room_group")
public class RoomGroup implements java.io.Serializable {

	private long roomGroupId;
	private Room room;
	private int roomGroup;

	public RoomGroup() {
	}

	public RoomGroup(long roomGroupId, Room room, int roomGroup) {
		this.roomGroupId = roomGroupId;
		this.room = room;
		this.roomGroup = roomGroup;
	}

	@SequenceGenerator(name="room_group_seq", sequenceName="room_group_room_group_id_seq")	@GeneratedValue(generator="room_group_seq")	@Id

	@Column(name = "room_group_id", unique = true, nullable = false)
	public long getRoomGroupId() {
		return this.roomGroupId;
	}

	public void setRoomGroupId(long roomGroupId) {
		this.roomGroupId = roomGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "room_group", nullable = false)
	public int getRoomGroup() {
		return this.roomGroup;
	}

	public void setRoomGroup(int roomGroup) {
		this.roomGroup = roomGroup;
	}

}
