package org.itri.view.humanhealth.hibernate;
// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RtMattressRecord generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "rt_mattress_record")
public class RtMattressRecord implements java.io.Serializable {

	private long rtMattressRecordId;
	private Sensor sensor;
	private String mattressData;
	private String mattressStatus;
	private Date lastUpdated;

	public RtMattressRecord() {
	}

	public RtMattressRecord(long rtMattressRecordId, Sensor sensor, String mattressData, String mattressStatus,
			Date lastUpdated) {
		this.rtMattressRecordId = rtMattressRecordId;
		this.sensor = sensor;
		this.mattressData = mattressData;
		this.mattressStatus = mattressStatus;
		this.lastUpdated = lastUpdated;
	}

	@SequenceGenerator(name="rt_mattress_record_seq", sequenceName="rt_mattress_record_rt_mattress_record_id_seq")	@GeneratedValue(generator="rt_mattress_record_seq")	@Id

	@Column(name = "rt_mattress_record_id", unique = true, nullable = false)
	public long getRtMattressRecordId() {
		return this.rtMattressRecordId;
	}

	public void setRtMattressRecordId(long rtMattressRecordId) {
		this.rtMattressRecordId = rtMattressRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sensor_id", nullable = false)
	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	@Column(name = "mattress_data", nullable = false, length = 64)
	public String getMattressData() {
		return this.mattressData;
	}

	public void setMattressData(String mattressData) {
		this.mattressData = mattressData;
	}

	@Column(name = "mattress_status", nullable = false, length = 32)
	public String getMattressStatus() {
		return this.mattressStatus;
	}

	public void setMattressStatus(String mattressStatus) {
		this.mattressStatus = mattressStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
