package org.itri.view.humanhealth.hibernate;
// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RtPmFiveRecord generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "rt_pm_five_record")
public class RtPmFiveRecord implements java.io.Serializable {

	private long rtPmFiveRecordId;
	private Sensor sensor;
	private String pmFiveData;
	private String pmFiveStatus;
	private Date lastUpdated;

	public RtPmFiveRecord() {
	}

	public RtPmFiveRecord(long rtPmFiveRecordId, Sensor sensor, String pmFiveData, String pmFiveStatus,
			Date lastUpdated) {
		this.rtPmFiveRecordId = rtPmFiveRecordId;
		this.sensor = sensor;
		this.pmFiveData = pmFiveData;
		this.pmFiveStatus = pmFiveStatus;
		this.lastUpdated = lastUpdated;
	}

	@SequenceGenerator(name="rt_pm_five_record_seq", sequenceName="rt_pm_five_record_rt_pm_five_record_id_seq")	@GeneratedValue(generator="rt_pm_five_record_seq")	@Id

	@Column(name = "rt_pm_five_record_id", unique = true, nullable = false)
	public long getRtPmFiveRecordId() {
		return this.rtPmFiveRecordId;
	}

	public void setRtPmFiveRecordId(long rtPmFiveRecordId) {
		this.rtPmFiveRecordId = rtPmFiveRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sensor_id", nullable = false)
	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	@Column(name = "pm_five_data", nullable = false, length = 64)
	public String getPmFiveData() {
		return this.pmFiveData;
	}

	public void setPmFiveData(String pmFiveData) {
		this.pmFiveData = pmFiveData;
	}

	@Column(name = "pm_five_status", nullable = false, length = 32)
	public String getPmFiveStatus() {
		return this.pmFiveStatus;
	}

	public void setPmFiveStatus(String pmFiveStatus) {
		this.pmFiveStatus = pmFiveStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
