package org.itri.view.humanhealth.hibernate;
// Generated 2020/4/24 �U�� 08:59:27 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RtTempPadRecord generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "rt_temp_pad_record")
public class RtTempPadRecord implements java.io.Serializable {

	private long rtTempPadRecordId;
	private Patient patient;
	private Sensor sensor;
	private String bodyTempData;
	private String batteryLevel;
	private String bodyTempStatus;
	private Date lastUpdated;

	public RtTempPadRecord() {
	}

	public RtTempPadRecord(long rtTempPadRecordId, Patient patient, Sensor sensor, String bodyTempData,
			String batteryLevel, String bodyTempStatus, Date lastUpdated) {
		this.rtTempPadRecordId = rtTempPadRecordId;
		this.patient = patient;
		this.sensor = sensor;
		this.bodyTempData = bodyTempData;
		this.batteryLevel = batteryLevel;
		this.bodyTempStatus = bodyTempStatus;
		this.lastUpdated = lastUpdated;
	}

	@SequenceGenerator(name="rt_temp_pad_record_seq", sequenceName="rt_temp_pad_record_rt_temp_pad_record_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="rt_temp_pad_record_seq")	@Id

	@Column(name = "rt_temp_pad_record_id", unique = true, nullable = false)
	public long getRtTempPadRecordId() {
		return this.rtTempPadRecordId;
	}

	public void setRtTempPadRecordId(long rtTempPadRecordId) {
		this.rtTempPadRecordId = rtTempPadRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sensor_id", nullable = false)
	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	@Column(name = "body_temp_data", nullable = false, length = 64)
	public String getBodyTempData() {
		return this.bodyTempData;
	}

	public void setBodyTempData(String bodyTempData) {
		this.bodyTempData = bodyTempData;
	}

	@Column(name = "battery_level", nullable = false, length = 64)
	public String getBatteryLevel() {
		return this.batteryLevel;
	}

	public void setBatteryLevel(String batteryLevel) {
		this.batteryLevel = batteryLevel;
	}

	@Column(name = "body_temp_status", nullable = false, length = 32)
	public String getBodyTempStatus() {
		return this.bodyTempStatus;
	}

	public void setBodyTempStatus(String bodyTempStatus) {
		this.bodyTempStatus = bodyTempStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
