package org.itri.view.humanhealth.hibernate;
// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SensorThreshold generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "sensor_threshold")
public class SensorThreshold implements java.io.Serializable {

	private long sensorThresholdId;
	private Users users;
	private HealthType healthType;
	private Sensor sensor;
	private String criticalLow;
	private String criticalHigh;
	private String durationTimes;
	private String dataName;
	private Date timeCreated;
	private Date lastUpdated;

	public SensorThreshold() {
	}

	public SensorThreshold(Users users, HealthType healthType, Sensor sensor,
			String durationTimes, Date timeCreated) {
		this.users = users;
		this.healthType = healthType;
		this.sensor = sensor;
		this.durationTimes = durationTimes;
		this.timeCreated = timeCreated;
	}
	
	public SensorThreshold(long sensorThresholdId, Users users, HealthType healthType, Sensor sensor,
			String durationTimes, Date timeCreated) {
		this.sensorThresholdId = sensorThresholdId;
		this.users = users;
		this.healthType = healthType;
		this.sensor = sensor;
		this.durationTimes = durationTimes;
		this.timeCreated = timeCreated;
	}

	public SensorThreshold(long sensorThresholdId, Users users, HealthType healthType, Sensor sensor, 
			String criticalLow, String criticalHigh, String durationTimes, String dataName,
			Date timeCreated, Date lastUpdated) {
		this.sensorThresholdId = sensorThresholdId;
		this.users = users;
		this.healthType = healthType;
		this.sensor = sensor;
		this.criticalLow = criticalLow;
		this.criticalHigh = criticalHigh;
		this.durationTimes = durationTimes;
		this.dataName = dataName;
		this.timeCreated = timeCreated;
		this.lastUpdated = lastUpdated;
	}

	@SequenceGenerator(name="sensor_threshold_seq", sequenceName="sensor_threshold_sensor_threshold_id_seq")	@GeneratedValue(generator="sensor_threshold_seq")	@Id

	@Column(name = "sensor_threshold_id", unique = true, nullable = false)
	public long getSensorThresholdId() {
		return this.sensorThresholdId;
	}

	public void setSensorThresholdId(long sensorThresholdId) {
		this.sensorThresholdId = sensorThresholdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "health_type_id", nullable = false)
	public HealthType getHealthType() {
		return this.healthType;
	}

	public void setHealthType(HealthType healthType) {
		this.healthType = healthType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sensor_id", nullable = false)
	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	@Column(name = "critical_low", length = 256)
	public String getCriticalLow() {
		return this.criticalLow;
	}

	public void setCriticalLow(String criticalLow) {
		this.criticalLow = criticalLow;
	}

	@Column(name = "critical_high", length = 256)
	public String getCriticalHigh() {
		return this.criticalHigh;
	}

	public void setCriticalHigh(String criticalHigh) {
		this.criticalHigh = criticalHigh;
	}

	@Column(name = "duration_times", nullable = false, length = 10)
	public String getDurationTimes() {
		return this.durationTimes;
	}

	public void setDurationTimes(String durationTimes) {
		this.durationTimes = durationTimes;
	}

	@Column(name = "data_name", length = 256)
	public String getDataName() {
		return this.dataName;
	}

	public void setDataName(String dataName) {
		this.dataName = dataName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", nullable = false, length = 29)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
}
