package org.itri.view.humanhealth.hibernate;
// Generated 2020/10/29 �U�� 04:58:12 by Hibernate Tools 4.0.0.Final
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sensor2healthType generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "sensor2health_type")
public class Sensor2healthType implements java.io.Serializable {

	private long sensor2healthTypeId;
	private HealthType healthType;
	private Sensor sensor;

	public Sensor2healthType() {
	}

	public Sensor2healthType(long sensor2healthTypeId, HealthType healthType, Sensor sensor) {
		this.sensor2healthTypeId = sensor2healthTypeId;
		this.healthType = healthType;
		this.sensor = sensor;
	}

	@SequenceGenerator(name="sensor2health_type_seq", sequenceName="sensor2health_type_sensor2health_type_id_seq")	@GeneratedValue(generator="sensor2health_type_seq")	@Id

	@Column(name = "sensor2health_type_id", unique = true, nullable = false)
	public long getSensor2healthTypeId() {
		return this.sensor2healthTypeId;
	}

	public void setSensor2healthTypeId(long sensor2healthTypeId) {
		this.sensor2healthTypeId = sensor2healthTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "health_type_id", nullable = false)
	public HealthType getHealthType() {
		return this.healthType;
	}

	public void setHealthType(HealthType healthType) {
		this.healthType = healthType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sensor_id", nullable = false)
	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

}
