package org.itri.view.humanhealth.hibernate;

import javax.persistence.GeneratedValue;
import javax.persistence.SequenceGenerator;
import javax.persistence.GenerationType;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SurveyQuestion generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "survey_question")
public class SurveyQuestion implements java.io.Serializable {

	private long surveyQuestionId;
	private String surveyQuestionText;
	private boolean isDeleted;
	private Set<SurveyQuestionChoice> surveyQuestionChoices = new HashSet<SurveyQuestionChoice>(0);
	private Set<SurveyResult> surveyResults = new HashSet<SurveyResult>(0);

	public SurveyQuestion() {
	}

	public SurveyQuestion(long surveyQuestionId, String surveyQuestionText, boolean isDeleted) {
		this.surveyQuestionId = surveyQuestionId;
		this.surveyQuestionText = surveyQuestionText;
		this.isDeleted = isDeleted;
	}

	public SurveyQuestion(long surveyQuestionId, String surveyQuestionText, boolean isDeleted,
			Set<SurveyQuestionChoice> surveyQuestionChoices, Set<SurveyResult> surveyResults) {
		this.surveyQuestionId = surveyQuestionId;
		this.surveyQuestionText = surveyQuestionText;
		this.isDeleted = isDeleted;
		this.surveyQuestionChoices = surveyQuestionChoices;
		this.surveyResults = surveyResults;
	}

	@SequenceGenerator(name = "survey_question_seq", sequenceName = "survey_question_survey_question_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "survey_question_seq")
	@Id

	@Column(name = "survey_question_id", unique = true, nullable = false)
	public long getSurveyQuestionId() {
		return this.surveyQuestionId;
	}

	public void setSurveyQuestionId(long surveyQuestionId) {
		this.surveyQuestionId = surveyQuestionId;
	}

	@Column(name = "survey_question_text", nullable = false, length = 1024)
	public String getSurveyQuestionText() {
		return this.surveyQuestionText;
	}

	public void setSurveyQuestionText(String surveyQuestionText) {
		this.surveyQuestionText = surveyQuestionText;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "surveyQuestion")
	public Set<SurveyQuestionChoice> getSurveyQuestionChoices() {
		return this.surveyQuestionChoices;
	}

	public void setSurveyQuestionChoices(Set<SurveyQuestionChoice> surveyQuestionChoices) {
		this.surveyQuestionChoices = surveyQuestionChoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "surveyQuestion")
	public Set<SurveyResult> getSurveyResults() {
		return this.surveyResults;
	}

	public void setSurveyResults(Set<SurveyResult> surveyResults) {
		this.surveyResults = surveyResults;
	}

}
