package org.itri.view.humanhealth.hibernate;

import javax.persistence.GeneratedValue;
import javax.persistence.SequenceGenerator;
import javax.persistence.GenerationType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SurveyQuestionChoice generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "survey_question_choice")
public class SurveyQuestionChoice implements java.io.Serializable {

	private long surveyQuestionChoiceId;
	private SurveyQuestion surveyQuestion;
	private String surveyQuestionChoiceText;
	private boolean isDeleted;

	public SurveyQuestionChoice() {
	}

	public SurveyQuestionChoice(long surveyQuestionChoiceId, SurveyQuestion surveyQuestion,
			String surveyQuestionChoiceText, boolean isDeleted) {
		this.surveyQuestionChoiceId = surveyQuestionChoiceId;
		this.surveyQuestion = surveyQuestion;
		this.surveyQuestionChoiceText = surveyQuestionChoiceText;
		this.isDeleted = isDeleted;
	}

	@SequenceGenerator(name = "survey_question_choice_seq", sequenceName = "survey_question_choice_survey_question_choice_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "survey_question_choice_seq")
	@Id

	@Column(name = "survey_question_choice_id", unique = true, nullable = false)
	public long getSurveyQuestionChoiceId() {
		return this.surveyQuestionChoiceId;
	}

	public void setSurveyQuestionChoiceId(long surveyQuestionChoiceId) {
		this.surveyQuestionChoiceId = surveyQuestionChoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "survey_question_id", nullable = false)
	public SurveyQuestion getSurveyQuestion() {
		return this.surveyQuestion;
	}

	public void setSurveyQuestion(SurveyQuestion surveyQuestion) {
		this.surveyQuestion = surveyQuestion;
	}

	@Column(name = "survey_question_choice_text", nullable = false, length = 1024)
	public String getSurveyQuestionChoiceText() {
		return this.surveyQuestionChoiceText;
	}

	public void setSurveyQuestionChoiceText(String surveyQuestionChoiceText) {
		this.surveyQuestionChoiceText = surveyQuestionChoiceText;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
